[package]
name = "leafbound"
version = "0.1.0"
description = "A calm, open-source EPUB reader for Windows."
authors = ["racode246"]
license = "MIT"
edition = "2021"
rust-version = "1.77"

[lib]
name = "leafbound_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-dialog = "2"
tauri-plugin-single-instance = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4"] }
epub = "2"
chrono = "0.4"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
